language: python
python:
    - "3.6"
    - "3.5"
env:
    - FLASK=1.0.2
    - FLASK=1.0
    - FLASK=0.12.1
install:
    - pip install flask==$FLASK
before_script:
script:
    - echo "Testing goes here"
    - flask --version
after_success:
    
after_failure:
before_deploy:
deploy:
  provider: elasticbeanstalk
  access_key_id: $ACCESSKEYID
  secret_access_key:
    secure: "$SECRETACCESSKEY"
  region: "us-east-1"  
  app: "travis-test"
  env: "TravisTest-env"
  bucket_name: "elasticbeanstalk-us-east-1-474625947253"
  on:
    branch: master
after_deploy:
after_script:
