language: python
python:
    - "3.6"
    - "3.5"
env:
    - FLASK=1.0.2
    - FLASK=1.0
    - FLASK=0.12.1
install:
    - pip install flask==$FLASK
before_script:
script:
    - echo "Testing goes here"
    - flask --version
