language: python
python:
    - "3.6"
    - "3.5"
env:
    - FLASK=dev
    - FLASK=1.0.2
    - FLASK=0.9
install:
    - pip install flask==$FLASK
script:
    - echo "Testing goes here"
    - flask --version
